/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.JUpdateController;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import model.AuthorModel;
import service.impl.AuthorService;
import service.impl.JUpdateService;

/**
 *
 * @author Gaara
 */
public class JUpdate extends javax.swing.JFrame {

    /**
     * Creates new form JAdminUpdate
     */
    public JUpdate() {
        this.setLocation(100, 10);
        initComponents();
        ActionListener action = new JUpdateController(this);
        btnAddBook.setEnabled(false);
        btnAddBook.addActionListener(action);
        btnFindBook.addActionListener(action);
        btnNewBook.addActionListener(action);
        btnEditBook.addActionListener(action);
        btnDelBook.addActionListener(action);
        btnBack.addActionListener(action);
        btnFindLoanSlip.addActionListener(action);
        btnNewLoanSlip.addActionListener(action);
        btnAddLoanSlip.addActionListener(action);
        btnEditLoanSlip.addActionListener(action);
        btnDelLoanSlip.addActionListener(action);
        btnPay.addActionListener(action);
        btnFindCustomer.addActionListener(action);
        btnNewCustomer.addActionListener(action);
        btnAddCustomer.addActionListener(action);
        btnEditCustomer.addActionListener(action);
        btnDelCustomer.addActionListener(action);

        txtID.setVisible(false);
        JUpdateService.loadData(tblBook);
        TableColumnModel columnModel = tblBook.getColumnModel();
        TableColumn column = columnModel.getColumn(0);
        tblBook.removeColumn(column);
        getDataRow(tblBook, 0);
        List<AuthorModel> authors = new AuthorService().findAllAuthors();
        cboAuthor.addItem("");
        for (AuthorModel author : authors) {
            cboAuthor.addItem(author.getName());
        }
    }

    public final void getDataRow(JTable table, int i) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) table.getModel();
        txtID.setText(String.valueOf(defaultTableModel.getValueAt(i, 0)));
        txtNameBook.setText((String) defaultTableModel.getValueAt(i, 1));
        txtNumber.setText(String.valueOf(defaultTableModel.getValueAt(i, 3)));
        String name = (String) defaultTableModel.getValueAt(i, 2);
        cboAuthor.getModel().setSelectedItem(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNameBook = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtFindBook = new javax.swing.JTextField();
        btnFindBook = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnAddBook = new javax.swing.JButton();
        btnEditBook = new javax.swing.JButton();
        btnDelBook = new javax.swing.JButton();
        btnNewBook = new javax.swing.JButton();
        cboAuthor = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtNameCustomer = new javax.swing.JTextField();
        txtBorrowedDay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBorrowed = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtFindLoanSlip = new javax.swing.JTextField();
        btnFindLoanSlip = new javax.swing.JButton();
        txtIdLoanSlip = new javax.swing.JTextField();
        btnAddLoanSlip = new javax.swing.JButton();
        btnEditLoanSlip = new javax.swing.JButton();
        btnDelLoanSlip = new javax.swing.JButton();
        btnNewLoanSlip = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        cboNameBorrowedBook = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtTenKhachHang = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhach = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtFindCustomer = new javax.swing.JTextField();
        btnFindCustomer = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtMaKhach = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        btnEditCustomer = new javax.swing.JButton();
        btnDelCustomer = new javax.swing.JButton();
        btnNewCustomer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Tên sách");

        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Tên sách", "Tên tác giả", "Số lượng"
            }
        ));
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBook);

        jLabel4.setText("Tên tác giả");

        btnFindBook.setText("Tìm sách");

        jLabel7.setText("Số lượng");

        btnAddBook.setText("Thêm sách");

        btnEditBook.setText("Sửa sách");
        btnEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookActionPerformed(evt);
            }
        });

        btnDelBook.setText("Xóa sách");

        btnNewBook.setText("Nhập sách mới");

        txtID.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnAddBook)
                .addGap(216, 216, 216)
                .addComponent(btnEditBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelBook)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnFindBook)
                        .addGap(18, 18, 18)
                        .addComponent(txtFindBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNewBook)
                        .addGap(159, 159, 159))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboAuthor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNameBook, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                        .addGap(157, 157, 157)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindBook)
                    .addComponent(btnNewBook))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBook)
                    .addComponent(btnEditBook)
                    .addComponent(btnDelBook))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cập nhật sách", jPanel2);

        jLabel19.setText("Mã phiếu mượn");

        jLabel20.setText("Tên Khách Hàng");

        tblBorrowed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phiếu mượn", "Tên khách hàng", "Tên sách", "Ngày mượn"
            }
        ));
        tblBorrowed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBorrowedMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBorrowed);

        jLabel21.setText("Tên sách");

        jLabel22.setText("Ngày mượn");

        btnFindLoanSlip.setText("Tìm phiếu mượn");
        btnFindLoanSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindLoanSlipActionPerformed(evt);
            }
        });

        btnAddLoanSlip.setText("Thêm phiếu mượn");
        btnAddLoanSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLoanSlipActionPerformed(evt);
            }
        });

        btnEditLoanSlip.setText("Sửa phiếu mượn");
        btnEditLoanSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLoanSlipActionPerformed(evt);
            }
        });

        btnDelLoanSlip.setText("Xóa phiếu mượn");
        btnDelLoanSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLoanSlipActionPerformed(evt);
            }
        });

        btnNewLoanSlip.setText("Nhập phiếu mượn mới");

        btnPay.setText("Trả sách");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdLoanSlip, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                    .addComponent(txtNameCustomer)
                                    .addComponent(cboNameBorrowedBook, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(btnFindLoanSlip)
                                .addGap(18, 18, 18)
                                .addComponent(txtFindLoanSlip, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnAddLoanSlip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditLoanSlip)
                                .addGap(82, 82, 82)
                                .addComponent(btnDelLoanSlip)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBorrowedDay, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNewLoanSlip)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btnPay)
                                .addGap(52, 52, 52)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindLoanSlip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindLoanSlip)
                    .addComponent(btnNewLoanSlip))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLoanSlip)
                    .addComponent(btnEditLoanSlip)
                    .addComponent(btnDelLoanSlip)
                    .addComponent(btnPay))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(txtIdLoanSlip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBorrowedDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cboNameBorrowedBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Cập nhật phiếu mượn", jPanel3);

        jLabel8.setText("Mã khách hàng");

        jLabel9.setText("Tên khách hàng");

        tblKhach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Email", "Số điện thoại"
            }
        ));
        tblKhach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhach);

        jLabel11.setText("Email");

        btnFindCustomer.setText("Tìm kiếm khách hàng");
        btnFindCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCustomerActionPerformed(evt);
            }
        });

        jLabel13.setText("Số điện thoại");

        btnAddCustomer.setText("Thêm khách hàng");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnEditCustomer.setText("Sửa khách hàng");
        btnEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerActionPerformed(evt);
            }
        });

        btnDelCustomer.setText("Xóa khách hàng");
        btnDelCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCustomerActionPerformed(evt);
            }
        });

        btnNewCustomer.setText("Nhập khách hàng mới");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(btnFindCustomer)
                                .addGap(18, 18, 18)
                                .addComponent(txtFindCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnAddCustomer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEditCustomer)
                                        .addGap(100, 100, 100))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                            .addComponent(txtTenKhachHang))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(txtPhone)
                            .addComponent(btnNewCustomer)
                            .addComponent(btnDelCustomer)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindCustomer)
                    .addComponent(btnNewCustomer))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnEditCustomer)
                    .addComponent(btnDelCustomer))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(txtMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Cập nhật khách hàng", jPanel1);

        btnBack.setText("Quay lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMouseClicked
        // TODO add your handling code here:

        this.btnAddBook.setEnabled(false);
        this.btnEditBook.setEnabled(true);
        this.btnDelBook.setEnabled(true);
        try {
            int row = this.tblBook.getSelectedRow();
            getDataRow(tblBook, row);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tblBookMouseClicked

    private void tblKhachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachMouseClicked
        // TODO add your handling code here:
//        ProcessCrt2(true);
//        this.btAddKhach.setEnabled(false);
//        try{
//            int row = this.tbKhach.getSelectedRow();
//            String IDrow = (this.tbKhach.getModel().getValueAt(row, 0)).toString();
//            String sql1 = "SELECT * FROM KHACH_HANG where Ma_Khach_hang='"+IDrow+"'";
//            ResultSet rs = UpdateTable.ShowTextField(sql1);
//            if(rs.next()) {
//                this.txtMaKhach.setText(rs.getString("Ma_Khach_hang"));
//                this.txtPassword.setText(rs.getString("Password"));
//                this.txtTenKhach.setText(rs.getString("Ten_Khach_hang"));
//                this.txtNgaySinh.setText(rs.getString("Ngay_sinh"));
//                this.txtDiaChi.setText(rs.getString("Dia_Chi"));
//                this.txtPhone.setText(rs.getString("Phone"));
//                
//            }
//        }catch(Exception e) {
//            
//        }
    }//GEN-LAST:event_tblKhachMouseClicked

    private void btnFindCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCustomerActionPerformed
        // TODO add your handling code here:
//        if(this.txtLookKhach.getText().length() == 0) {
//            String sql1 = "SELECT * from KHACH_HANG ";
//            UpdateTable.LoadData(sql1, tbKhach);
//        }
//        else {
//            String sql1 = "SELECT * from KHACH_HANG WHERE Ma_Khach_hang like N'%"+this.txtLookKhach.getText()+"%' "
//                    + "or Ten_Khach_hang like N'%"+this.txtLookKhach.getText()+"%' or Phone like '%"+this.txtLookKhach.getText()+"%'"
//                    +"or Mail like N'%"+this.txtLookKhach.getText()+"%'";
//            UpdateTable.LoadData(sql1, tbKhach);
//        }
    }//GEN-LAST:event_btnFindCustomerActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
//        try{
//             if (this.txtMaKhach.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã khách hàng không thể bỏ trống", "thông báo", 2);
//            else if(this.txtMaKhach.getText().length()>10) JOptionPane.showMessageDialog(null, "Mã khách hàng không được lớn hơn 10 ký tự", "thông báo", 2);
//            else {
//            KhachHang s = new KhachHang(this.txtMaKhach.getText(), this.txtPassword.getText(), this.txtTenKhach.getText(),Date.valueOf(this.txtNgaySinh.getText()),
//            this.txtDiaChi.getText(),this.txtPhone.getText());
//            KhachHangData.InsertKhachHang(s);
//            this.btLookKhach.doClick();
//        }
//        }catch(Exception e) {
//            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
//        }
//        
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomerActionPerformed
        // TODO add your handling code here:
//        if (this.txtMaKhach.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã khách hàng không thể bỏ trống", "thông báo", 2);
//        else if(this.txtMaKhach.getText().length()>10) JOptionPane.showMessageDialog(null, "Mã khách hàng không được lớn hơn 10 ký tự", "thông báo", 2);
//        else {
//            KhachHang s = new KhachHang(this.txtMaKhach.getText(), this.txtPassword.getText(), this.txtTenKhach.getText(),Date.valueOf(this.txtNgaySinh.getText()),
//            this.txtDiaChi.getText(),this.txtPhone.getText());
//            if(khachhangdata.UpdateKhachHang(s)) {
//                JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công", "Thông báo", 1);
//            }
//            else JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
//            this.btLookKhach.doClick();
//        }
    }//GEN-LAST:event_btnEditCustomerActionPerformed

    private void btnDelCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCustomerActionPerformed
        // TODO add your handling code here:
//        if (this.txtMaKhach.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã sách không thể bỏ trống", "thông báo", 2);
//        else if(this.txtMaKhach.getText().length()>10) JOptionPane.showMessageDialog(null, "Mã sách không được lớn hơn 10 ký tự", "thông báo", 2);
//        else {
//            if(khachhangdata.DeleteKhachHang(this.txtMaKhach.getText())) {
//                JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công", "Thông báo", 1);
//            }
//            else JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
//            this.btLookKhach.doClick();
//        }
    }//GEN-LAST:event_btnDelCustomerActionPerformed

    private void tblBorrowedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBorrowedMouseClicked
        // TODO add your handling code here:
//        ProcessCrt3(true);
//        this.btAddPhieu.setEnabled(false);
//        try{
//            int row = this.tbMuon.getSelectedRow();
//            String IDrow = (this.tbMuon.getModel().getValueAt(row, 0)).toString();
//            String sql1 = "SELECT * FROM PHIEU_MUON where Ma_Phieu_muon='"+IDrow+"'";
//            ResultSet rs = UpdateTable.ShowTextField(sql1);
//            if(rs.next()) {
//                this.txtMaPhieuMuon.setText(rs.getString("Ma_Phieu_muon"));
//                this.txtNguoiMuon.setText(rs.getString("Ma_Khach_hang"));
//                this.txtSachMuon.setText(rs.getString("Ma_Sach"));
//                this.txtNgayMuon.setText(rs.getString("Ngay_muon"));
//                this.txtHanTra.setText(rs.getString("Han_tra"));
//                
//            }
//        }catch(Exception e) {
//            
//        }
    }//GEN-LAST:event_tblBorrowedMouseClicked

    private void btnFindLoanSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindLoanSlipActionPerformed
        // TODO add your handling code here:
//        if(this.txtLookPhieu.getText().length() == 0) {
//            String sql1 = "SELECT * from PHIEU_MUON ";
//            UpdateTable.LoadData(sql1, tbMuon);
//        }
//        else {
//            String sql1 = "SELECT * from PHIEU_MUON WHERE Ma_Phieu_muon like N'%"+this.txtLookPhieu.getText()+"%' "
//                    + "or Ma_Khach_hang like N'%"+this.txtLookPhieu.getText()+"%' or Ma_Sach like N'%"+this.txtLookPhieu.getText()+"%'";
//            UpdateTable.LoadData(sql1, tbMuon);
//        }
    }//GEN-LAST:event_btnFindLoanSlipActionPerformed

    private void btnAddLoanSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLoanSlipActionPerformed
        // TODO add your handling code here
//        try{
//             if (this.txtMaPhieuMuon.getText().length()==0 ) 
//                 JOptionPane.showMessageDialog(null, "Mã phiếu mượn không thể bỏ trống", "thông báo", 2);
//            else if(this.txtMaPhieuMuon.getText().length()>10) JOptionPane.showMessageDialog(null, "Mã phiếu mượn không được lớn hơn 10 ký tự", "thông báo", 2);
//            else {
//            PhieuMuon p = new PhieuMuon(this.txtMaPhieuMuon.getText(),this.txtNguoiMuon.getText(),this.txtSachMuon.getText(),
//                    Date.valueOf(this.txtNgayMuon.getText()),Date.valueOf(this.txtHanTra.getText()));
//            PhieuMuonData.InsertPhieu(p);
//            this.btLookMuon.doClick();
//        }
//        }catch(Exception e) {
//            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
//        }
//        
//        String sql = "UPDATE SACH SET So_luong = ? where Ma_Sach = ?";
//        String sql1 = "SELECT So_luong from SACH where Ma_Sach = '"+this.txtSachMuon.getText()+"'";
//        try {
//            ps = Connect.getConnect().prepareStatement(sql);
//            ResultSet rs = UpdateTable.ShowTextField(sql1);
//            ps.setString(2,this.txtSachMuon.getText());
//            int count = 0;
//            if(rs.next()) count = rs.getInt("So_luong");
//            ps.setInt(1, count-1);
//            ps.execute();
//            this.btLookSach.doClick();
//        } catch (Exception ex) {
//        }
//        
    }//GEN-LAST:event_btnAddLoanSlipActionPerformed

    private void btnEditLoanSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLoanSlipActionPerformed
        // TODO add your handling code here:
//        if (this.txtMaPhieuMuon.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã phiếu mượn không thể bỏ trống", "thông báo", 2);
//        else if(this.txtMaPhieuMuon.getText().length()>10) JOptionPane.showMessageDialog(null, "Mã phiếu mượn không được lớn hơn 10 ký tự", "thông báo", 2);
//        else {
//            PhieuMuon p = new PhieuMuon(this.txtMaPhieuMuon.getText(), this.txtNguoiMuon.getText(),
//                    this.txtSachMuon.getText(),Date.valueOf(this.txtNgayMuon.getText()),Date.valueOf(this.txtHanTra.getText()));
//            if(phieumuondata.UpdatePhieu(p)) {
//                JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công", "Thông báo", 1);
//            }
//            else JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
//            this.btLookMuon.doClick();
//        }
    }//GEN-LAST:event_btnEditLoanSlipActionPerformed

    private void btnDelLoanSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLoanSlipActionPerformed
        // TODO add your handling code here:
//        if (this.txtMaPhieuMuon.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã phiếu không thể bỏ trống", "thông báo", 2);
//        else if(this.txtMaPhieuMuon.getText().length()>10) JOptionPane.showMessageDialog(null, "Mã phiếu không được lớn hơn 10 ký tự", "thông báo", 2);
//        else {
//            if(phieumuondata.DeletePhieu(this.txtMaPhieuMuon.getText())) {
//                JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công", "Thông báo", 1);
//            }
//            else JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
//            this.btLookMuon.doClick();
//        }
    }//GEN-LAST:event_btnDelLoanSlipActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:

//        String sql = "UPDATE SACH SET So_luong = ? where Ma_Sach = ?";
//        String sql1 = "SELECT So_luong from SACH where Ma_Sach = '"+this.txtSachMuon.getText()+"'";
//        String sql2 = "UPDATE PHIEU_MUON SET NgayTra = (select GETDATE()) where Ma_Phieu_muon = ?";
//        
//        
//        try {
//            ps2 = Connect.getConnect().prepareStatement(sql2);
//            ps2.setString(1, this.txtMaPhieuMuon.getText());
//            ps2.executeQuery();
//            this.btLookMuon.doClick();
//            
//            ps = Connect.getConnect().prepareStatement(sql);
//            ResultSet rs = UpdateTable.ShowTextField(sql1);
//            ps.setString(2,this.txtSachMuon.getText());
//            int count = 0;
//            if(rs.next()) count = rs.getInt("So_luong");
//            
//            ps.setInt(1, count+1);
//            ps.execute();
//            this.btLookMuon.doClick();
//        } catch (Exception ex) {
//        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookActionPerformed
        // TODO add your handling code here:
        //        if (this.txtMaSach.getText().length()==0) JOptionPane.showMessageDialog(null, "Mã sách không thể bỏ trống", "thông báo", 2);
        //        else if(this.txtMaSach.getText().length()>10) JOptionPane.showMessageDialog(null, "Mã sách không được lớn hơn 10 ký tự", "thông báo", 2);
        //        else {
            //            Sach s = new Sach(this.txtMaSach.getText(), this.txtTenSach.getText(), this.txtTenTacGia.getText(),this.txtNhaXb.getText(),
                //             Integer.parseInt(this.txtGia.getText()),Integer.parseInt(this.txtSoLuong.getText()));
            //            if(sachdata.UpdateSach(s)) {
                //                JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công", "Thông báo", 1);
                //            }
            //            else JOptionPane.showMessageDialog(null, "Có lỗi xảy ra", "Thông báo", 2);
            //            this.btLookSach.doClick();
            //        }
    }//GEN-LAST:event_btnEditBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JUpdate().setVisible(true);
        });
    }

    public JTable getTbSach() {
        return tblBook;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddBook;
    public javax.swing.JButton btnAddCustomer;
    public javax.swing.JButton btnAddLoanSlip;
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnDelBook;
    public javax.swing.JButton btnDelCustomer;
    public javax.swing.JButton btnDelLoanSlip;
    public javax.swing.JButton btnEditBook;
    public javax.swing.JButton btnEditCustomer;
    public javax.swing.JButton btnEditLoanSlip;
    public javax.swing.JButton btnFindBook;
    public javax.swing.JButton btnFindCustomer;
    public javax.swing.JButton btnFindLoanSlip;
    public javax.swing.JButton btnNewBook;
    public javax.swing.JButton btnNewCustomer;
    public javax.swing.JButton btnNewLoanSlip;
    public javax.swing.JButton btnPay;
    public javax.swing.JComboBox<String> cboAuthor;
    public javax.swing.JComboBox<String> cboNameBorrowedBook;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable tblBook;
    public javax.swing.JTable tblBorrowed;
    public javax.swing.JTable tblKhach;
    public javax.swing.JTextField txtBorrowedDay;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtFindBook;
    public javax.swing.JTextField txtFindCustomer;
    public javax.swing.JTextField txtFindLoanSlip;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtIdLoanSlip;
    public javax.swing.JTextField txtMaKhach;
    public javax.swing.JTextField txtNameBook;
    public javax.swing.JTextField txtNameCustomer;
    public javax.swing.JTextField txtNumber;
    public javax.swing.JTextField txtPhone;
    public javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
